spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mycalendar
    password: mycalendar

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
